apiVersion: v1
kind: Secret
metadata:
  name: gameserver-pro-secrets
  namespace: gameserver-pro
type: Opaque
data:
  POSTGRES_PASSWORD: ZThEUGZRczAzUWJPeVN5allJNXZaWU03cE5Cd0ZwdDFaVUtBdzJhTlV2Yz0=
  JWT_SECRET: Z3JxU2NiTk1EWlduMmVsUWlvWUJwdGtpcS9LTUNHMHdwOG94Vk1sQ01GYWxyc1NnOGhMNmtlbHI1UlZKMDYxegp4QTN1dmYwVWlnN2RKOWUydVR5SWxRPT0=
  ENCRYPTION_KEY: NTYxZDhlNDY3MTJhMmMzNGVlYTIzOGM2ZjRhNDBmZGFkYTBjYjIxMGQ4MTNiYmZkNzc5YTg3NjI3YTgwMDgwNA==
  REDIS_PASSWORD: NlVsczJzNnR6aDZnaHBxL2lSUHBkWjZQWU1PcXpkdHNBVzFWM2VrajRZWT0=
  PAYMENT_GATEWAY_KEY: eW91cl9wYXltZW50X2dhdGV3YXlfa2V5X2hlcmU=
